### ISSUE TITLE
Inconsistent behavior of Client.fetch_friends() and Client.fetch_full_friends()

### ISSUE THREAD

**Issue by ShingenPizza** [vrchatapi/VRChatPython#16]
`fetch_friends()` docstring has
```
offline, boolean
Get offline friends instead of online friends
```
and that's correct.

However, `fetch_full_friends()` docstring has
```
offline, boolean
Include offline friends or not
```
and that's wrong.
`fetch_full_friends()` uses `fetch_friends()` just once, passing all parameters there, so as a result `fetch_full_friends(offline=True)` does not **include** offline friends, but gets them instead.
Also the default value of `offline` is `True` in `fetch_full_friends()` and `False` in  `fetch_friends()`.

I suggest either
a) change the docstring and the default value of `fetch_full_friends()`,
b) or add an additional `fetch_friends(offline=False)` there to make it work the way it's described,
c) or, preferably, do a) + add an option to get both offline and online friends with one call by setting `offline` to `None`?

**Comment by Katistic** [comment]
Thank you for pointing this out! I have corrected the description of the offline kwarg.

**Comment by ShingenPizza** [comment]
Uhh that same docstring is in the async version too.

Also again, there's this weird situation that calling `fetch_full_friends()` without specifying `offline` gives the opposite results than calling `fetch_friends()` without specifying it. Do you really want to keep it like that? I'd keep both `False`.

**Comment by Katistic** [comment]
I've changed the kwarg default to false and fixed up the async docs too, I haven't pushed them yet though
