### ISSUE TITLE
vrcpy.errors.IntegretyError - what to do?

### ISSUE THREAD

**Issue by royalroadprog** [vrchatapi/VRChatPython#25]
I got the message "vrcpy.errors.IntegretyError: Object does not have unique key (pluginUrl) for World (Class definition may be outdated, please make an issue on github)" while running it through Heroku.

**Comment by CaptainDestructo** [comment]
Are you running the latest version? There was a recent patch

**Comment by royalroadprog** [comment]
I believe Heroku will automatically use the latest version from PyPI but the latest release date [here](https://pypi.org/project/vrcpy/) was Nov 27, 2020.

**Comment by CaptainDestructo** [comment]
There’s been an update since then. Use the most recent code from this repo.

**Comment by royalroadprog** [comment]
Solved by changing the dependency to repo instead. Thank you.
